image: python:3.7

stages:
  - test
  - quality-assurance

before_script:
  - pip install tox

py37-django22:
  image: python:3.7
  stage: test
  script: tox -e py37-django22

py37-django30:
  image: python:3.7
  stage: test
  script: tox -e py37-django30

linters:
  image: python:3.7
  stage: quality-assurance
  script: tox -e linters
