# Generated by Django 3.0.2 on 2020-02-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/unknown.png', upload_to='avatars'),
        ),
    ]
