# Generated by Django 3.0.2 on 2020-02-14 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0018_auto_20200201_0509'),
        ('codeflix', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cfuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeforces.CodeforcesUser'),
        ),
    ]
