# Generated by Django 3.0.1 on 2019-12-22 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=255, unique=True, verbose_name='Handle')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('vkid', models.CharField(blank=True, max_length=255)),
                ('openid', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Organization')),
                ('contribution', models.IntegerField(verbose_name='User contribution')),
                ('rank', models.CharField(blank=True, max_length=255, verbose_name='Rank')),
                ('max_rating', models.CharField(blank=True, max_length=255, verbose_name='Max Rating')),
                ('last_online_time_seconds', models.BigIntegerField(verbose_name='Time, when user was last seen online, in UNIX format.')),
                ('registration_time_seconds', models.BigIntegerField(verbose_name='Time, when user was registered, in UNIX format.')),
                ('friend_of_count', models.IntegerField(verbose_name='Amount of users who have this user in friends.')),
                ('database_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
