# Generated by Django 3.0.1 on 2020-01-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(verbose_name='Id of the contest.')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the contest.')),
                ('type', models.CharField(choices=[('CF', 'CF'), ('IOI', 'IOI'), ('ICPC', 'ICPC')], max_length=255, verbose_name='Scoring system used for the contest.')),
                ('phase', models.CharField(choices=[('BEFORE', 'BEFORE'), ('CODING', 'CODING'), ('PENDING_SYSTEM_TEST', 'PENDING_SYSTEM_TEST'), ('SYSTEM_TEST', 'SYSTEM_TEST'), ('FINISHED', 'FINISHED')], max_length=255, verbose_name='Current phase of the contest.')),
                ('frozen', models.BooleanField()),
                ('duration_seconds', models.IntegerField(verbose_name='Duration of the contest in seconds.')),
                ('start_time_seconds', models.BigIntegerField(blank=True, verbose_name='Contest start time in unix format.')),
                ('relative_time_seconds', models.BigIntegerField(blank=True, verbose_name='Number of seconds, passed after the start of the contest.')),
                ('difficulty', models.IntegerField(blank=True, verbose_name='Larger number means more difficult problems')),
            ],
        ),
    ]
