# Generated by Django 3.0.1 on 2020-01-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0002_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='useful',
            field=models.BooleanField(default=False, verbose_name='Is this contest useful for codeflix ?'),
        ),
    ]
