# Generated by Django 3.0.1 on 2020-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0006_codeforcesuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcesuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's avatar URL."),
        ),
        migrations.AddField(
            model_name='codeforcesuser',
            name='title_photo',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's title photo URL."),
        ),
    ]
