# Generated by Django 3.0.1 on 2020-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0007_auto_20200128_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcesuser',
            name='max_rank',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's max rank."),
        ),
    ]
