# Generated by Django 2.2.6 on 2020-01-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0008_codeforcesuser_max_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeforcesuser',
            old_name='vkid',
            new_name='vk_id',
        ),
    ]
