# Generated by Django 2.2.6 on 2020-01-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0009_auto_20200128_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeforcesuser',
            old_name='openid',
            new_name='open_id',
        ),
    ]
