# Generated by Django 3.0.2 on 2020-02-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0011_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='The name of the tag.')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='codeforces.ProblemTag', verbose_name='List of tags for the problem.'),
        ),
    ]
