# Generated by Django 3.0.2 on 2020-02-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0012_auto_20200201_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='codeforces.Problem', verbose_name='The list of problems of this contest.'),
        ),
    ]
