# Generated by Django 3.0.2 on 2020-02-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0013_contest_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(null=True, verbose_name='Id of the contest for which this attempt was made.')),
                ('solved', models.BooleanField(default=False, verbose_name='Was this submission a success ?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.CodeforcesUser', verbose_name='Author of this attempt')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.Problem', verbose_name='The problem for which this is an attempt.')),
            ],
        ),
    ]
