# Generated by Django 3.0.2 on 2020-02-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0014_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='contest_id',
        ),
        migrations.AddField(
            model_name='attempt',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeforces.Contest', verbose_name='Contest for which this attempt was made.'),
        ),
    ]
