# Generated by Django 3.0.2 on 2020-02-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0016_auto_20200201_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcesuser',
            name='avatar',
            field=models.CharField(max_length=255, null=True, verbose_name="User's avatar URL."),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='max_rank',
            field=models.CharField(max_length=255, null=True, verbose_name="User's max rank."),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='max_rating',
            field=models.IntegerField(null=True, verbose_name='Max Rating'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='open_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='organization',
            field=models.CharField(max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='rank',
            field=models.CharField(max_length=255, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='title_photo',
            field=models.CharField(max_length=255, null=True, verbose_name="User's title photo URL."),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='vk_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
