# Generated by Django 3.0.3 on 2020-02-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0019_remove_codeforcesuser_database_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcesuser',
            name='recommended_problems',
            field=models.ManyToManyField(blank=True, to='codeforces.Problem', verbose_name='The list of problems recommended for this user.'),
        ),
    ]
